version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - .:/web/php-fpm-nginx

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    volumes:
      - .:/web/php-fpm-nginx
    ports:
      - ${PORT_NGINX_HTTP:-80}:80
      - ${PORT_NGINX_HTTPS:-443}:81
